In [4]:
import numpy as np

In [ ]:
#1 Initialize an empty array with size 2X2.
empty_array=np.empty((2,2))
print("Empty Array (2*2):\n",empty_array)

Empty Array (2x2):
[[4.88820935e-310 0.00000000e+000]
 [3.45845952e-323             nan]]


In [ ]:
#2 Initialize an all one array with size 4X2.
ones_array=np.ones((4,2))
print("All one array with size (4x2) is:",ones_array)

All one array with size (4x2) is: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3 Return a new array of given shape and type, filled with fill value.{Hint: np.full}
filled_array=np.full((3,3),5)
print("Filled array with fill value and type:",filled_array)

Filled array with fill value and type: [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#4 Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
zero_array=np.zeros_like(filled_array)
print("Zero array is:",zero_array)

Zero array is: [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#5 Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
ones_array=np.ones_like(filled_array)
print("Ones array is:",ones_array)

Ones array is: [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#6 For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list=[1,2,3,4]
numpy_array=np.array(new_list)
print("Numpy array is:",numpy_array)

Numpy array is: [1 2 3 4]


In [ ]:
#Problem2 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
arrange_array = np.arange(10, 50)
print("Arranged array with values ranging from 10 to 49 is:", arrange_array)


Arranged array with values ranging from 10 to 49 is: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#2 Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
reshape_array=np.arange(9).reshape(3,3)
print("Reshaped array is:",reshape_array)


Reshaped array is: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#3Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix=np.eye(3,3)
print("Identitiy matrix :",identity_matrix)

Identitiy matrix : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#4 Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}
random_array=np.random.random(30)
mean_value=random_array.mean()
print("Random array:",random_array)
print("\nMean of the array is:",mean_value)

Random array: [0.35906903 0.60063053 0.40783092 0.02440039 0.21709558 0.00262677
 0.32797939 0.17795426 0.05299823 0.68680522 0.46069079 0.99684178
 0.85185027 0.76476743 0.50968953 0.78898534 0.17723274 0.13385639
 0.50434889 0.92721567 0.00771176 0.97904179 0.32937745 0.25352857
 0.87193307 0.93991358 0.99081893 0.58256698 0.41244701 0.75942606]

Mean of the array is: 0.5033211453345735


In [11]:
#5 Create a 10X10 array with random values and find the minimum and maximum values.
random_array = np.random.random((10, 10))

min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 array:",random_array)
print("\nMinimum value:", min_value,"and the Maxium value is:",max_value)



Random 10x10 array: [[0.41447724 0.5021952  0.34347665 0.02668226 0.88681614 0.76221678
  0.52825185 0.74297276 0.10527127 0.7357881 ]
 [0.10597104 0.66272749 0.45406014 0.82242169 0.8379571  0.34503209
  0.12205052 0.39477036 0.03845163 0.83066313]
 [0.50315524 0.24898172 0.70228006 0.95311981 0.11170489 0.42173424
  0.56100861 0.16587844 0.7998999  0.41868897]
 [0.77007006 0.14660835 0.19146803 0.82457202 0.43307165 0.30183541
  0.58527203 0.91548968 0.6134258  0.41494136]
 [0.01331103 0.7629476  0.92686005 0.46075997 0.86148226 0.83758423
  0.99956213 0.9615438  0.3076577  0.95172429]
 [0.13847944 0.65070014 0.01993692 0.63014476 0.70810338 0.12076688
  0.42914971 0.52992505 0.55401681 0.16597492]
 [0.1141989  0.60304985 0.5111389  0.22177768 0.42764495 0.01495978
  0.8723044  0.15277938 0.20121402 0.82693181]
 [0.24071461 0.71336491 0.8320199  0.74595657 0.4638064  0.9720354
  0.89544026 0.89339953 0.53514508 0.78824513]
 [0.52370049 0.90877813 0.63897498 0.4654682  0.40839246 0.87

In [12]:
#6 Create a zero array of size 10 and replace 5th element with 1.
zero_array=np.zeros(10)
zero_array[4]=1
print("Modified array",zero_array)


Modified array [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
#7 Reverse an array arr = [1,2,0,0,4,0].
reverse_array=[1,2,0,0,4,0]
reverse_array.reverse()
print("Reversed array is:",reverse_array)

Reversed array is: [0, 4, 0, 0, 2, 1]


In [17]:
#8 Create a 2d array with 1 on border and 0 inside.
import numpy as np

rows, cols = 4, 4
array = np.zeros((rows, cols), dtype=int)
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print("2D array with border of 1s and inside 0s:",array)



2D array with border of 1s and inside 0s:
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [18]:
#9 Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("Checkerboard pattern:",checkerboard)


Checkerboard pattern: [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
# Problem 3
# For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);

#1 Add the two array.

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result = x + y

print("Sum of x and y:",result)



Sum of x and y: [[ 6  8]
 [10 13]]


In [21]:
#2 Subtract the two array.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result = x - y

print("Subtraction of x and y:",result)

Subtraction of x and y: [[-4 -4]
 [-4 -3]]


In [22]:
#3 Multiply the array with any integers of your choice.

y = np.array([[5, 6], [7, 8]])

result = y*3

print("Multiplication of y:",result)

Multiplication of y: [[15 18]
 [21 24]]


In [23]:
#4 Find the square of each element of the array.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result_x = x**2
result_y=y**2

print("Square of x is:",result_x)
print("Square of y:",result_y)

Square of x is: [[ 1  4]
 [ 9 25]]
Square of y: [[25 36]
 [49 64]]


In [24]:
#5 Find the dot product between: v(and)w ; x(and)v ; x(and)y.

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)

dot_xv = np.dot(x, v)

dot_xy = np.dot(x, y)

print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:", dot_xv)
print("Dot product of x and y:", dot_xy)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


In [25]:
#6 Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_xy_rows = np.concatenate((x, y), axis=0)

v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)
concat_vw_columns = np.concatenate((v_reshaped, w_reshaped), axis=1)

print("Concatenated x and y along rows:")
print(concat_xy_rows)

print("Concatenated v and w along columns:")
print(concat_vw_columns)


Concatenated x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


In [27]:
#7 Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

try:
    result = np.concatenate((x, v), axis=0)
    print("Concatenated x and v:")
    print(result)
except Exception as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [29]:
# Problem 4
#1 • For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
# 2. Prove AB ̸= BA.
# 3. Prove (AB)
# T = BTAT


A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A_inv = I
A_inv = np.linalg.inv(A)
result_1 = np.dot(A, A_inv)

# 2. Prove A * B != B * A
AB = np.dot(A, B)
BA = np.dot(B, A)

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

# Print results
print("A * A_inv:",result_1)
print("\nA * B:",AB)

print("\nB * A:",BA)

print("\nTranspose of A * B:",AB_T)

print("\nB^T * A^T:",B_T_A_T)



A * A_inv: [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

A * B: [[23 13]
 [51 29]]

B * A: [[36 44]
 [13 16]]

Transpose of A * B: [[23 51]
 [13 29]]

B^T * A^T: [[23 51]
 [13 29]]


In [32]:
#2 Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])


A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution (x, y, z):", X)


Solution (x, y, z): [ 2.  1. -2.]


In [33]:
#3 Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
import numpy as np


A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

X = np.linalg.inv(A).dot(B)

print("Solution (x, y, z):", X)


Solution (x, y, z): [ 2.  1. -2.]
